name: API CI

on:
  push: 
    branches: [main, develop]
  pull_request:
    branches: [main, develop]


jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v4 #git clone runner

      - name: setup Nodejs
          uses: actions/setup-node@v4
            with:
              node-version: 20 
        
      - name: Install Dependencies
      - run: npm install

      - name: run unit test
      - run: npm run test

      - name: run code linter
      - run: npm run lint 
